name: deploy production

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 #Checkout repository
            - uses: actions/setup-node@v4 #Set up Node.js
              with:
                  node-version: 20.x.x
                  cache: npm
            - run: npm ci #Install dependencies
            - run: npm run lint #Checking the code for errors
    deploy:
        needs: lint
        runs-on: ubuntu-latest
        concurrency:
            group: prod
            cancel-in-progress: true
        steps:
            # Checkout the repository
            - uses: actions/checkout@v4

            # Set up Node.js
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x.x
                  cache: npm

            # Install dependencies
            - run: npm ci

            # Build the project (assuming a Next.js project)
            - run: npm run build

            # Docker setup (if you используете Docker для деплоя)
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            # Build Docker image
            - name: Build Docker image
              run: docker build -t my-nextjs-app .
